name: James L Stockman Income Tax Service
favicon: null
layout_spectrum: 0.75352
typography_spectrum: 0.74654
title: James L Stockman Income Tax Service
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#766e63'
    - '#aca59d'
    - '#454140'
    - '#e0dfdd'
    - '#c3c2bd'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
